LUAC = "C:/Program Files (x86)/Gideros/Tools/luac.exe"

all: .tmp/main.lua.bin .tmp/json.lua.bin .tmp/api.lua.bin .tmp/commands.lua.bin .tmp/flag.lua.bin .tmp/layer.lua.bin .tmp/bar.lua.bin .tmp/text.lua.bin .tmp/util.lua.bin .tmp/gtween.lua.bin .tmp/easing.lua.bin .tmp/alert.lua.bin .tmp/spinner.lua.bin .tmp/random.lua.bin .tmp/msgbox.lua.bin .tmp/block.lua.bin

.tmp/main.lua.bin: main.lua
	$(LUAC) -o ".tmp/main.lua.bin" "main.lua"

.tmp/json.lua.bin: json.lua
	$(LUAC) -o ".tmp/json.lua.bin" "json.lua"

.tmp/api.lua.bin: api.lua
	$(LUAC) -o ".tmp/api.lua.bin" "api.lua"

.tmp/commands.lua.bin: commands.lua
	$(LUAC) -o ".tmp/commands.lua.bin" "commands.lua"

.tmp/flag.lua.bin: flag.lua
	$(LUAC) -o ".tmp/flag.lua.bin" "flag.lua"

.tmp/layer.lua.bin: layer.lua
	$(LUAC) -o ".tmp/layer.lua.bin" "layer.lua"

.tmp/bar.lua.bin: bar.lua
	$(LUAC) -o ".tmp/bar.lua.bin" "bar.lua"

.tmp/text.lua.bin: text.lua
	$(LUAC) -o ".tmp/text.lua.bin" "text.lua"

.tmp/util.lua.bin: util.lua
	$(LUAC) -o ".tmp/util.lua.bin" "util.lua"

.tmp/gtween.lua.bin: gtween.lua
	$(LUAC) -o ".tmp/gtween.lua.bin" "gtween.lua"

.tmp/easing.lua.bin: easing.lua
	$(LUAC) -o ".tmp/easing.lua.bin" "easing.lua"

.tmp/alert.lua.bin: alert.lua
	$(LUAC) -o ".tmp/alert.lua.bin" "alert.lua"

.tmp/spinner.lua.bin: spinner.lua
	$(LUAC) -o ".tmp/spinner.lua.bin" "spinner.lua"

.tmp/random.lua.bin: random.lua
	$(LUAC) -o ".tmp/random.lua.bin" "random.lua"

.tmp/msgbox.lua.bin: msgbox.lua
	$(LUAC) -o ".tmp/msgbox.lua.bin" "msgbox.lua"

.tmp/block.lua.bin: block.lua
	$(LUAC) -o ".tmp/block.lua.bin" "block.lua"

